### ISSUE TITLE
DeltaMonitor not cleared on backtracks

### ISSUE THREAD

**Issue by JLiangWaterloo** [chocoteam/choco3#298]
Perhaps my understanding of DeltaMonitor is incorrect but I did not expect the following code to throw an error with the latest develop branch.

```java
public static void main(String[] args) {
    Solver s = new Solver();
    final IntVar i = VF.enumerated("i", -2, 2, s);
    final IntVar j = VF.enumerated("j", -2, 2, s);
    // Does nothing, just observes the values removed from variables i and j.
    Propagator p1 = new Propagator(new IntVar[]{i, j}, PropagatorPriority.UNARY, false) {

        private final IIntDeltaMonitor iD = i.monitorDelta(aCause);
        private final IIntDeltaMonitor jD = j.monitorDelta(aCause);

        @Override
        public void propagate(int evtmask) throws ContradictionException {
            iD.freeze();
            iD.forEachRemVal((IntProcedure) x -> {
                System.out.println("Delta monitor for variable says that the value " + x + " is removed from variable i");
                if (i.contains(x)) {
                    throw new Error("Delta monitor lied to me.");
                }
            });
            iD.unfreeze();
            jD.freeze();
            jD.forEachRemVal((IntProcedure) x -> {
                System.out.println("Delta monitor for variable says that the value " + x + " is removed from variable j");
                if (j.contains(x)) {
                    throw new Error("Delta monitor lied to me.");
                }
            });
            jD.unfreeze();
        }

        @Override
        public ESat isEntailed() {
            return ESat.TRUE;
        }
    };
    // if j == 1 then i != 1.
    Propagator p2 = new Propagator(new IntVar[]{i, j}, PropagatorPriority.UNARY, false) {

        @Override
        public void propagate(int evtmask) throws ContradictionException {
            if (j.isInstantiatedTo(1)) {
                i.removeValue(1, aCause);
            }
        }

        @Override
        public ESat isEntailed() {
            return ESat.TRUE;
        }
    };
    Chatterbox.showDecisions(s);
    Chatterbox.showSolutions(s);
    s.post(new Constraint("Constraint", p1, p2));
    s.findAllSolutions();
}
```

The above code will print:
```
...[L]j  ==  -2 (0) //i = {-2,-1,0,1,2} j = {-2,-1,0,1,2} 
Delta monitor for variable says that the value -1 is removed from variable j
Delta monitor for variable says that the value 0 is removed from variable j
Delta monitor for variable says that the value 1 is removed from variable j
Delta monitor for variable says that the value 2 is removed from variable j
....[L]i  ==  -2 (0) //i = {-2,-1,0,1,2} j = -2 
Delta monitor for variable says that the value -1 is removed from variable i
Delta monitor for variable says that the value 0 is removed from variable i
Delta monitor for variable says that the value 1 is removed from variable i
Delta monitor for variable says that the value 2 is removed from variable i
Delta monitor for variable says that the value -1 is removed from variable j
Delta monitor for variable says that the value 0 is removed from variable j
Delta monitor for variable says that the value 1 is removed from variable j
Delta monitor for variable says that the value 2 is removed from variable j
- Solution #1 found. 1 Solutions, Resolution 0.112s, 3 Nodes (26.9 n/s), 0 Backtracks, 0 Fails, 0 Restarts 
	i = -2 j = -2 .
....[R]i  ==  -2 (1) //i = {-2,-1,0,1,2} j = -2 
Delta monitor for variable says that the value -2 is removed from variable i
.....[L]i  ==  -1 (0) //i = {-1,0,1,2} j = -2 
Delta monitor for variable says that the value 0 is removed from variable i
Delta monitor for variable says that the value 1 is removed from variable i
Delta monitor for variable says that the value 2 is removed from variable i
- Solution #2 found. 2 Solutions, Resolution 0.138s, 5 Nodes (36.2 n/s), 1 Backtracks, 0 Fails, 0 Restarts 
	i = -1 j = -2 .
.....[R]i  ==  -1 (1) //i = {-1,0,1,2} j = -2 
Delta monitor for variable says that the value -1 is removed from variable i
......[L]i  ==  0 (0) //i = {0,1,2} j = -2 
Delta monitor for variable says that the value 1 is removed from variable i
Delta monitor for variable says that the value 2 is removed from variable i
- Solution #3 found. 3 Solutions, Resolution 0.142s, 7 Nodes (49.4 n/s), 2 Backtracks, 0 Fails, 0 Restarts 
	i = 0 j = -2 .
......[R]i  ==  0 (1) //i = {0,1,2} j = -2 
Delta monitor for variable says that the value 0 is removed from variable i
.......[L]i  ==  1 (0) //i = {1,2} j = -2 
Delta monitor for variable says that the value 2 is removed from variable i
- Solution #4 found. 4 Solutions, Resolution 0.150s, 9 Nodes (60.1 n/s), 3 Backtracks, 0 Fails, 0 Restarts 
	i = 1 j = -2 .
.......[R]i  ==  1 (1) //i = {1,2} j = -2 
Delta monitor for variable says that the value 1 is removed from variable i
- Solution #5 found. 5 Solutions, Resolution 0.151s, 10 Nodes (66.3 n/s), 4 Backtracks, 0 Fails, 0 Restarts 
	i = 2 j = -2 .
...[R]j  ==  -2 (1) //i = {-2,-1,0,1,2} j = {-2,-1,0,1,2} 
Delta monitor for variable says that the value 1 is removed from variable i
Exception in thread "main" java.lang.Error: Delta monitor lied to me.
	at org.clafer.choco.constraint.propagator.PropReifyEqualXY$3.lambda$propagate$7ffb7347$1(PropReifyEqualXY.java:132)
	at org.clafer.choco.constraint.propagator.PropReifyEqualXY$3$$Lambda$4/511754216.execute(Unknown Source)
	at org.chocosolver.solver.variables.delta.monitor.EnumDeltaMonitor.forEachRemVal(EnumDeltaMonitor.java:93)
	at org.clafer.choco.constraint.propagator.PropReifyEqualXY$3.propagate(PropReifyEqualXY.java:129)
	at org.chocosolver.solver.propagation.hardcoded.SevenQueuesPropagatorEngine.propagate(SevenQueuesPropagatorEngine.java:190)
	at org.chocosolver.solver.search.loop.SearchLoop.downBranch(SearchLoop.java:407)
	at org.chocosolver.solver.search.loop.SearchLoop.downRightBranch(SearchLoop.java:397)
	at org.chocosolver.solver.search.loop.SearchLoop.loop(SearchLoop.java:288)
	at org.chocosolver.solver.search.loop.SearchLoop.launch(SearchLoop.java:193)
	at org.chocosolver.solver.Solver.solve(Solver.java:891)
	at org.chocosolver.solver.Solver.findAllSolutions(Solver.java:767)
	at org.clafer.choco.constraint.propagator.PropReifyEqualXY.main(PropReifyEqualXY.java:169)
```

**Comment by jgFages** [comment]
Your usage of delta monitor is incorrect:

Delta monitors are used for incremental propagation only: 
- The third argument in the propagator super constructor should be "true"
- The method propagate(int e) will be called ONCE (further propagations will be incremental). It should not use the deltamonitors but UNFREEZE them at the end (in order to initialize the datastructure).
- You must then override the propagate(int vIdx, int e) method that is called whenever vars[vIdx] has changed. Then you can use the deltamonitor of that variable as you did (freeze, use, unfreeze).

See PropEqualX_Y or PropInverseChannelAC for an example. 

Actually, delta monitors are not used that much...

**Comment by JLiangWaterloo** [comment]
My bad, thanks.

**Comment by JLiangWaterloo** [comment]
I made the 3 changes you suggested and I still get the exact same error, see updated code snippet below:

```java
public static void main(String[] args) {
    Solver s = new Solver();
    final IntVar i = VF.enumerated("i", -2, 2, s);
    final IntVar j = VF.enumerated("j", -2, 2, s);
    // Does nothing, just observes the values removed from variables i and j.
    Propagator p1 = new Propagator(new IntVar[]{i, j}, PropagatorPriority.UNARY, true) {

        private final IIntDeltaMonitor iD = i.monitorDelta(aCause);
        private final IIntDeltaMonitor jD = j.monitorDelta(aCause);

        @Override
        public void propagate(int evtmask) throws ContradictionException {
            iD.unfreeze();
            jD.unfreeze();
        }

        @Override
        public void propagate(int idxVarInProp, int mask) throws ContradictionException {
            iD.freeze();
            iD.forEachRemVal((IntProcedure) x -> {
                System.out.println("Delta monitor for variable says that the value " + x + " is removed from variable i");
                if (i.contains(x)) {
                    throw new Error("Delta monitor lied to me.");
                }
            });
            iD.unfreeze();
            jD.freeze();
            jD.forEachRemVal((IntProcedure) x -> {
                System.out.println("Delta monitor for variable says that the value " + x + " is removed from variable j");
                if (j.contains(x)) {
                    throw new Error("Delta monitor lied to me.");
                }
            });
            jD.unfreeze();
        }

        @Override
        public ESat isEntailed() {
            return ESat.TRUE;
        }
    };
    // if j == 1 then i != 1.
    Propagator p2 = new Propagator(new IntVar[]{i, j}, PropagatorPriority.UNARY, false) {

        @Override
        public void propagate(int evtmask) throws ContradictionException {
            if (j.isInstantiatedTo(1)) {
                i.removeValue(1, aCause);
            }
        }

        @Override
        public ESat isEntailed() {
            return ESat.TRUE;
        }
    };
    Chatterbox.showDecisions(s);
    Chatterbox.showSolutions(s);
    s.post(new Constraint("Constraint", p1, p2));
    s.findAllSolutions();
}
```

> Actually, delta monitors are not used that much...

There are 20 propagators/views in the choco 3 library that use IIntDeltaMonitor. Quite a few of classes in my own project uses them as well.

**Comment by cprudhom** [comment]
Thank you for the bug reporting, I found where this comes from. I'll fix that asap.

**Comment by cprudhom** [comment]
Actually, I think your code is not correct either: you should not iterate over removed values of a variable which has not been modified since the last call of the propagator.
In the code of your first propagator, there should be a condition on `idxVarInProp`.

**Comment by cprudhom** [comment]
Finally, I rollback my patch since your code was not correct. I add a error message, though, when delta and deltamonitors are not synchronized (actually, it is an assertion error, but I'm considering moving it to a standard error, even if it may lead to performance issues).
