### ISSUE TITLE
TwoBucketPropagationEngine doesn't work in 3.3.2

### ISSUE THREAD

**Issue by gregy4** [chocoteam/choco3#346]
Hello,

  TwoBucketPropagationEngine is unfunctional for my problem in 3.3.2, following exception is thrown. When SevenQueuesPropagatorEngine was used, no problem happened but as in previous versions of choco3 performance is very bad compared to TwoBucketPropagationEngine.

  No explicit propagation happened before start of the solver.

  Tomorrow I can try to make minimal example for testing of the issue.

Best regards,
Jan

Exception in thread "main" org.chocosolver.solver.exception.SolverException: Cannot schedule coarse event for low priority propagator.
	at org.chocosolver.solver.propagation.hardcoded.TwoBucketPropagationEngine.delayedPropagation(TwoBucketPropagationEngine.java:375)
	at org.chocosolver.solver.constraints.Propagator.forcePropagate(Propagator.java:316)
	at org.chocosolver.solver.constraints.nary.sum.PropSumBoolIncr.propagate(PropSumBoolIncr.java:114)
	at org.chocosolver.solver.propagation.hardcoded.TwoBucketPropagationEngine.propagateFine(TwoBucketPropagationEngine.java:257)
	at org.chocosolver.solver.propagation.hardcoded.TwoBucketPropagationEngine.propagate(TwoBucketPropagationEngine.java:212)
	at org.chocosolver.solver.search.loop.PropagateBasic.execute(PropagateBasic.java:47)
	at org.chocosolver.solver.search.loop.SearchLoop.launch(SearchLoop.java:206)
	at org.chocosolver.solver.Solver.solve(Solver.java:1099)
	at org.chocosolver.solver.Solver.findOptimalSolution(Solver.java:1000)
	at org.chocosolver.solver.Solver.findOptimalSolution(Solver.java:1012)

**Comment by cprudhom** [comment]
I finally reproduce your case. I let you know when the patch is ready to be released.

**Comment by gregy4** [comment]
Great, thanks for fast response.

**Comment by cprudhom** [comment]
This has to do with the incremental version of `PropBoolSum` which is a low priority propagator, and low priority propagators are not allowed to delayed coarse propagation.

A quick fix is to change `Settings.java` to disable the use of the incremental version of the propagator:
```java
Solver solver = new Solver();
solver.set(new Settings() {
    @Override
    public boolean enableIncrementalityOnBoolSum(int nbvars) {
        // return nbvars > 10; // default test
        return false;
    }
});
``` 

Another patch, closest to the correction I'll bring, would be to allow low priority propagator to schedule coarse propagation :
```java 
Solver solver = new Solver();
solver.set(new Settings() {
    @Override
    public short[] getCoarseEventPriority() {
        return new short[]{0, 0, 0, 0, 1, 2, 3};
    }
});
```
Indeed, I need to re-evaluate the possibility to schedule low priority propagator.

**Comment by gregy4** [comment]
Both quick fixes seem to work.
