### ISSUE TITLE
Large Neighborhood Search doesn't work in 3.3.2

### ISSUE THREAD

**Issue by gregy4** [chocoteam/choco3#357]
Hello,
  today I tried to use LNS in choco 3.3.2, unfortunatelly it seems that it isn't functional.
Following exception is thrown ...

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 64
	at org.chocosolver.solver.search.strategy.decision.IntMetaDecision.add(IntMetaDecision.java:74)
	at org.chocosolver.solver.search.strategy.decision.IntMetaDecision.add(IntMetaDecision.java:64)
	at org.chocosolver.solver.search.loop.lns.neighbors.PropagationGuidedNeighborhood.impose(PropagationGuidedNeighborhood.java:163)
	at org.chocosolver.solver.search.loop.lns.neighbors.PropagationGuidedNeighborhood.update(PropagationGuidedNeighborhood.java:130)
	at org.chocosolver.solver.search.loop.lns.neighbors.PropagationGuidedNeighborhood.fixSomeVariables(PropagationGuidedNeighborhood.java:113)
	at org.chocosolver.solver.search.loop.lns.neighbors.SequenceNeighborhood.fixSomeVariables(SequenceNeighborhood.java:70)
	at org.chocosolver.solver.search.loop.MoveLNS.extend(MoveLNS.java:111)
	at org.chocosolver.solver.search.loop.SearchLoop.launch(SearchLoop.java:221)
	at org.chocosolver.solver.Solver.solve(Solver.java:1099)
	at org.chocosolver.solver.Solver.findOptimalSolution(Solver.java:1000)
	at org.chocosolver.solver.Solver.findOptimalSolution(Solver.java:1012)

LNS was invoked with
     LNSFactory.pglns(solver, solver.retrieveIntVars(), 30, 0, 5, 100, new FailCounter(solver, 100));
     LNSFactory.rlns(solver, solver.retrieveIntVars(), 30, 0, new FailCounter(solver, 100));

Since the methods does return void I'm not able (or don't know how) to active LNS after some threshold (like node count without a solution).

**Comment by gregy4** [comment]
Quick investigation showed that in IntMetaDecision are three arrays initialized to size = 64, method increase() updates size of var and val arrays but third array dop isn't fixed so ArrayIndexOutOfBoundsException is thrown.
