### ISSUE TITLE
Tuple out of memory for simple multiplication

### ISSUE THREAD

**Issue by JLiangWaterloo** [chocoteam/choco3#358]
For example, run the following code.

```java
Solver s = new Solver();
IntVar x = VF.enumerated("x", new int[]{1, 10}, s);
IntVar y = VF.enumerated("y", new int[]{1, 10000}, s);
IntVar z = VF.enumerated("z", new int[]{10, 10000}, s);
ICF.times(x, y, z);
```

This will throw the error:

```java
Exception in thread "main" org.chocosolver.solver.exception.SolverException: Tuples required over 50Mo of memory...
	at org.chocosolver.solver.constraints.extension.nary.TuplesTable.<init>(TuplesTable.java:88)
	at org.chocosolver.solver.constraints.extension.nary.PropLargeGAC3rm.makeRelation(PropLargeGAC3rm.java:106)
	at org.chocosolver.solver.constraints.extension.nary.PropLargeGAC3rm.makeRelation(PropLargeGAC3rm.java:106)
	at org.chocosolver.solver.constraints.extension.nary.PropLargeGAC3rm.<init>(PropLargeGAC3rm.java:92)
	at org.chocosolver.solver.constraints.IntConstraintFactory.table(IntConstraintFactory.java:1485)
	at org.chocosolver.solver.constraints.IntConstraintFactory.times(IntConstraintFactory.java:436)
```

So IntConstraintFactory.tupleIt returned true, yet creating the table itself failed.

**Comment by cprudhom** [comment]
Thank you for the bug report.
The tests are not correct. I have to change them in order to consider using very large table instead of large table. Indeed, one test considers the domain sizes (here 2*2*2 = 8) and another one considers the difference between bounds (here 9999 * 9999 * 9 = 899820009).

**Comment by JLiangWaterloo** [comment]
Thanks for the fix!
